version: 1.0.{build}
image: Visual Studio 2019
build_script:
  - cmd: >-
      set MSYSTEM=MINGW64

      xcopy %CD% C:\msys64\home\appveyor\davif /e/i/h

      C:\msys64\usr\bin\bash -lc "pacman -S mingw-w64-x86_64-dlfcn mingw-w64-x86_64-nasm mingw-w64-x86_64-cmake --noconfirm"

      C:\msys64\usr\bin\bash -lc "cd davif && git submodule update --init --recursive"

      C:\msys64\usr\bin\bash -lc "cd davif && mkdir build && cd build && cmake .. -G 'MSYS Makefiles' -DCMAKE_CXX_FLAGS=-static && make -j4 && strip davif.exe"

      7z a davif-win64.7z "C:\msys64\home\appveyor\davif\build\*.exe"

artifacts:
  - path: davif-win64.7z

deploy:
  - provider: GitHub
    artifact: davif-win64.7z           # upload all NuGet packages to release assets
    auth_token:
      secure: QbQ70S0qrbv9+8H3lkzRjFK5dNjb0bZdktusi/mgRlrw2O6iaglZDu6wbU203tLE
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
