name: Build on macOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        sed -i -e 's/git\@github\.com\:/https\:\/\/github.com\//g' .gitmodules
        git submodule init
        git submodule sync --recursive
        git submodule update
        git submodule foreach bash -c "sed -i -e 's/git\@github\.com\:/https\:\/\/github.com\//g' .gitmodules || true"
        git submodule foreach git submodule sync --recursive
        git submodule foreach git submodule init
        git submodule foreach git submodule update --init --force --recursive
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install wheel
        pip3 install meson
        pip3 install ninja
        brew install yasm
    - name: configure
      shell: bash
      run: |
        export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
        source venv/bin/activate
        cmake -S . -B build
    - name: make
      shell: bash
      run: |
        export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
        source venv/bin/activate
        (cd build && make)
